---
- name: Create a file to be used as swap space
  community.general.filesize:
    path: "{{ swapfile_path }}"
    size: "{{ swapfile_size }}"
    blocksize: "{{ swapfile_blocksize }}"
    mode: u=rw,go=
    owner: root
    group: root
  when: ansible_swaptotal_mb < 1

- name: Format the file for swap
  ansible.builtin.command:
    cmd: "mkswap {{ swapfile_path }}"
  register: swapfile_formatted
  changed_when: swapfile_formatted.rc == 0
  when: ansible_swaptotal_mb < 1

- name: Add the file to the system as a swap file
  ansible.builtin.command:
    cmd: "swapon {{ swapfile_path }}"
  register: swapfile_added
  changed_when: swapfile_added.rc == 0
  when: ansible_swaptotal_mb < 1
