---
- name: Create a file to be used as swap space
  community.general.filesize:
    path: /var/swapfile
    size: 2G
    blocksize: 512B
    mode: u=rw,go=
    owner: root
    group: root
  when: ansible_swaptotal_mb < 1

- name: Format the file for swap
  ansible.builtin.command: mkswap /var/swapfile
  register: swapfile_formatted
  changed_when: swapfile_formatted.rc == 0
  when: ansible_swaptotal_mb < 1

- name: Add the file to the system as a swap file
  ansible.builtin.command: swapon /var/swapfile
  register: swapfile_added
  changed_when: swapfile_added.rc == 0
  when: ansible_swaptotal_mb < 1
