---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Make sure swap space is created.
      ansible.builtin.debug:
        var: ansible_facts.swaptotal_mb

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
